import Providers from "@/components/providers/Providers";
import "@/styles/globals.css";
import { Toaster } from "sonner";

import { type Metadata } from "next";
import { Outfit } from "next/font/google";
import { auth } from "@clerk/nextjs/server";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${outfit.className}`}>
      <body>
        <Toaster richColors />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
